argo_url: 'https://argo-qa.stanford.edu'
dor_services:
  url: 'https://dor-services-qa-lb.stanford.edu'
etd_url: 'https://etd-qa.stanford.edu'
h2_url: 'https://sul-h2-qa.stanford.edu'
h2_url: 'https://sul-h3-qa.stanford.edu'
preassembly:
  host: 'sul-preassembly-qa.stanford.edu'
  url: 'https://sul-preassembly-qa.stanford.edu'
sdrapi_url: 'https://sdr-api-qa.stanford.edu'
was_playback_url: 'https://swap-qa.stanford.edu'
was_registrar:
  host: 'was-registrar-app-qa.stanford.edu'
  jobs_directory: '/was_unaccessioned_data/jobs'
  url: 'https://was-registrar-app-qa.stanford.edu'
  username: 'was'
speech_to_text:
  enabled: true
