argo_url: 'https://argo-stage.stanford.edu'
dor_services:
  url: 'https://dor-services-stage-lb.stanford.edu'
etd_url: 'https://etd-stage.stanford.edu'
h2_url: 'https://sul-h2-stage.stanford.edu'
preassembly:
  host: 'sul-preassembly-stage.stanford.edu'
  url: 'https://sul-preassembly-stage.stanford.edu'
sdrapi_url: 'https://sdr-api-stage.stanford.edu'
was_playback_url: 'https://swap-stage.stanford.edu'
was_registrar:
  host: 'was-registrar-app-stage.stanford.edu'
  jobs_directory: '/was_unaccessioned_data/jobs'
  url: 'https://was-registrar-app-stage.stanford.edu'
  username: 'was'
